services:
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jogo-baralho-tests
    entrypoint: ["dotnet", "test"]
    networks:
      - jogo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jogodebaralho-backend
    ports:
      - "5000:8080"
    depends_on:
      backend-tests:
        condition: service_completed_successfully
    networks:
      - jogo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jogodebaralho-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - jogo-network

networks:
  jogo-network:
    driver: bridge